# Generated by Django 5.0.2 on 2024-11-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_tag_game_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
    ]
